name: tourism_app
description: The tourism app application is a platform that provides information to help users explore tourist destinations.

publish_to: "none"

version: 1.0.2+4

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2

  http: 1.2.0
  bloc: 8.1.3
  flutter_bloc: 8.1.4
  get_it: 7.6.7
  url_launcher: 6.2.5
  font_awesome_flutter: 10.7.0
  hydrated_bloc: 9.1.4
  path_provider: 2.1.2
  shorebird_code_push: 1.1.3
  pub_semver: 2.1.4
  pusher_beams: 1.1.1
  restart_app: 1.2.1
  firebase_core: 2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - shorebird.yaml
